#!/usr/bin/env ruby

require_relative File.join(__dir__, 'react_create_section')
require_relative File.join(__dir__, 'react_create_hooks')
require_relative File.join(__dir__, 'react_create_hooks_test')

puts '--------------------------------------------------'
print "Enter Section Name: "
sectionName = gets.chomp
puts '''
--------------------------------------------------
Example Input : doLogin,forgotPassword.

Generator will generate as interface of controller.
You need to change specific return if needed later.

Enter Function In Controller Presentation (separated with comma) : 
'''
functionNames = gets.chomp

if sectionName.length > 1
	
  section_command = create_section(
    component_name: sectionName
  )

  hooks_command = create_hooks(
    component_name: sectionName,
    function_names: functionNames,
    from:'section'
  )

  test_command = create_hooks_test(
    component_name: sectionName,
    function_names: functionNames,
    from:'section'
  )
  

	exec(
    "cd src && " +
    section_command +
    hooks_command +
    test_command
	)
else
	puts "Please enter Section name!"
end
