#!/usr/bin/env ruby

require_relative File.join(__dir__, 'react_example_base_api')
require_relative File.join(__dir__, 'react_example_hooks')
require_relative File.join(__dir__, 'react_example_pages')
require_relative File.join(__dir__, 'react_example_paths')
require_relative File.join(__dir__, 'react_example_routes')
require_relative File.join(__dir__, 'react_example_services')
require_relative File.join(__dir__, 'react_example_types')
require_relative File.join(__dir__, 'react_example_utils')
require_relative File.join(__dir__, 'react_example_store')
require_relative File.join(__dir__, 'react_config_vite')
require_relative File.join(__dir__, 'react_config_prettier')
require_relative File.join(__dir__, 'react_config_css')
require_relative File.join(__dir__, 'react_config_main')
require_relative File.join(__dir__, 'react_config_eslint')
require_relative File.join(__dir__, 'react_config_env')
require_relative File.join(__dir__, 'react_config_tsconfig')

print "Enter Project Name: "
projectName = gets.chomp

if projectName.length > 1
	createProject = "npm create vite@latest " + projectName + " -- --template react-ts"
	
  createPackages = 	
    "&& cd " + projectName + 
		"&& touch sonar.properties " +
		"&& npm install @reduxjs/toolkit @tailwindcss/vite @types/node @types/react @types/react-dom @vitejs/plugin-react-swc react-redux react-dom react-hook-form react-router tailwind zod  "

	createStructureComponents = 
    "&& cd src " +
		"&& mkdir components " +
    "&& mkdir constants " +
    "&& cd constants " +
    "&& mkdir enums " +
    "&& mkdir items " +
    "&& mkdir schemas " +
    "&& cd .. " +
    "&& mkdir hooks " +
    "&& mkdir pages " +
    "&& mkdir routes " +
    "&& mkdir services " +
    "&& mkdir stores " +
    "&& mkdir styles " +
    "&& mkdir types && cd types && mkdir responses && mkdir requests && mkdir parameters && cd .. " +
    "&& mkdir utils "
  

	createStructure = "cd " + projectName + createStructureComponents

  createExampleAPI = create_example_base_api
  createExampleHooks = create_example_hooks
  createExamplePages = create_example_pages
  createExamplePaths = create_example_paths
  createExampleRoutes = create_example_routes
  createExampleServices = create_example_services
  createExampleTypes = create_example_types
  createExampleUtils = create_example_utils
  createExampleStore = create_example_store
  createConfigVite = create_config_vite
  createConfigEnv = create_config_env
  createConfigEslint = create_config_eslint
  createConfigCSS = create_config_css
  createConfigMain = create_config_main
  createConfigTSConfig = create_config_tsconfig

  createConfigPrettier = create_config_prettier
  move_prettier_config = "&& mv .prettierrc #{projectName}/.prettierrc"
	exec(
	createProject +
  createPackages +
	createStructure +
  createExampleAPI +
  createExampleHooks +
  createExamplePages +
  createExamplePaths +
  createExampleRoutes +
  createExampleServices +
  createExampleTypes + #error here
  createExampleUtils + 
  createExampleStore + 
  createConfigCSS + 
  createConfigMain +
  " cd .. && " +
  createConfigVite +
  createConfigEnv +
  createConfigTSConfig +
  createConfigEslint + 
   "cd .. " +
  move_prettier_config
	)
else
	puts "Please enter project name!"
end
